services:
  timescaledb:
    image: timescale/timescaledb:latest-pg14
    container_name: fcore_db
    environment:
      - POSTGRES_USER=fcoreuser
      - POSTGRES_PASSWORD=GaboPassword
      - POSTGRES_DB=fcoredb
    ports:
      - "5433:5432"
    volumes:
      - fcore_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  fcore_data:
